---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
#  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
#  security_group_ids: ["sg-1a2b3c4d"]
  region: eu-west-1
  availability_zone: b
  require_chef_omnibus: true
#  subnet_id: subnet-6e5d4c3b
#  iam_profile_name: chef-client
  instance_type: t2.micro
  associate_public_ip: true

provisioner:
  name: chef_solo
  require_chef_omnibus: latest

transport:
  ssh_key: travis.pem
  connection_timeout: 10
  connection_retries: 5

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  driver:
    image_id: ami-273c4250
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list: ["recipe[java_wrapper_test]"]
  attributes:
    java:
      install_flavour: openjdk
      jdk_version: 7
      set_etc_environment: true
