---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  driver_config:
    customize:
      memory: 1024
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      memory: 1024
#- name: ubuntu-10.04
#  driver_config:
#    box: opscode-ubuntu-10.04
#    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
#- name: centos-6.4
#  driver_config:
#    box: opscode-centos-6.4
#    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
#- name: centos-5.9
#  driver_config:
#    box: opscode-centos-5.9
#    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list: ["recipe[apt]", "recipe[test_java_wrapper]"]
  attributes:
    play2:
      version: 2.1.3
      checksum: 03ee0b6971c2f325a2a012470040b4104e2b58ef48d32767c0fd690e5c6cac48
