---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
#  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
#  security_group_ids: ["sg-1a2b3c4d"]
  region: eu-west-1
  availability_zone: b
  require_chef_omnibus: true
#  subnet_id: subnet-6e5d4c3b
#  iam_profile_name: chef-client
  instance_type: m3.medium
  associate_public_ip: true

provisioner:
  name: chef_solo
  require_chef_omnibus: latest

platforms:

- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list: ["recipe[test_java_wrapper]"]
  attributes:
    java:
      install_flavour: openjdk
      jdk_version: 7
      set_etc_environment: true
