language: ruby
bundler_args: "--without kitchen_vagrant --without development"
rvm:
- 2.1.0
cache:
  bundler: true
script:
- bundle exec rake travis --trace
after_script:
- bundle exec kitchen destroy
env:
  global:
  - KITCHEN_YAML=.kitchen.cloud.yml
matrix:
- KITCHEN_INSTANCE='default-ubuntu-1404'
- KITCHEN_INSTANCE='default-ubuntu-1204'
before_install:
- openssl aes-256-cbc -K $encrypted_6e60153793b3_key -iv $encrypted_6e60153793b3_iv
  -in travis.pem.enc -out travis.pem -d
